CREATE TABLE [dbo].[ACCOUNT_CHAR](
	[strAccountID] [char](21) NOT NULL,
	[bNation] [tinyint] NOT NULL,
	[bCharNum] [tinyint] NOT NULL,
	[strCharID1] [char](21) NULL,
	[strCharID2] [char](21) NULL,
	[strCharID3] [char](21) NULL,
	[strCharID4] [char](21) NULL,
	[strCharID5] [char](21) NULL,
 CONSTRAINT [PK_ACCOUNT_CHAR] PRIMARY KEY CLUSTERED 
(
	[strAccountID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];

ALTER TABLE [dbo].[ACCOUNT_CHAR] ADD  CONSTRAINT [DF_ACCOUNT_CHAR_bCharNum]  DEFAULT ((0)) FOR [bCharNum];
