CREATE TABLE [dbo].[KNIGHTS](
	[IDNum] [smallint] NOT NULL,
	[Flag] [tinyint] NOT NULL,
	[Nation] [tinyint] NOT NULL,
	[Ranking] [tinyint] NOT NULL,
	[IDName] [char](21) NOT NULL,
	[Members] [smallint] NOT NULL,
	[Chief] [char](21) NOT NULL,
	[ViceChief_1] [char](21) NULL,
	[ViceChief_2] [char](21) NULL,
	[ViceChief_3] [char](21) NULL,
	[Gold] [bigint] NOT NULL,
	[Domination] [smallint] NOT NULL,
	[Points] [int] NULL,
	[CreateTime] [smalldatetime] NOT NULL,
	[Mark] [image] NULL,
	[Stash] [varchar](1600) NULL,
 CONSTRAINT [PK_KNIGHTS] PRIMARY KEY CLUSTERED 
(
	[IDNum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

SET ANSI_PADDING ON

/****** Object:  Index [IX_KNIGHTS]    Script Date: 10/11/2023 3:18:58 AM ******/
ALTER TABLE [dbo].[KNIGHTS] ADD  CONSTRAINT [IX_KNIGHTS] UNIQUE NONCLUSTERED 
(
	[IDName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]

ALTER TABLE [dbo].[KNIGHTS] ADD  CONSTRAINT [DF_KNIGHTS_Flag]  DEFAULT ((1)) FOR [Flag]

ALTER TABLE [dbo].[KNIGHTS] ADD  CONSTRAINT [DF_KNIGHTS_Ranking]  DEFAULT ((0)) FOR [Ranking]

ALTER TABLE [dbo].[KNIGHTS] ADD  CONSTRAINT [DF_KNIGHTS_Members]  DEFAULT ((1)) FOR [Members]

ALTER TABLE [dbo].[KNIGHTS] ADD  CONSTRAINT [DF_KNIGHTS_Gold]  DEFAULT ((0)) FOR [Gold]

ALTER TABLE [dbo].[KNIGHTS] ADD  CONSTRAINT [DF_KNIGHTS_Domination]  DEFAULT ((0)) FOR [Domination]

ALTER TABLE [dbo].[KNIGHTS] ADD  CONSTRAINT [DF_KNIGHTS_Points]  DEFAULT ((0)) FOR [Points]

ALTER TABLE [dbo].[KNIGHTS] ADD  CONSTRAINT [DF_KNIGHTS_CreateTime]  DEFAULT (getdate()) FOR [CreateTime]

