CREATE TABLE [dbo].[MAGIC_TYPE2](
	[iNum] [int] NOT NULL,
	[Name] [char](30) NOT NULL,
	[Description] [char](100) NULL,
	[HitType] [tinyint] NOT NULL,
	[HitRate] [smallint] NOT NULL,
	[AddDamage] [smallint] NOT NULL,
	[AddRange] [smallint] NOT NULL,
	[NeedArrow] [tinyint] NOT NULL,
	[AddDamagePlus] [smallint] NOT NULL,
 CONSTRAINT [PK_MAGIC_TYPE2] PRIMARY KEY CLUSTERED 
(
	[iNum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (102003, N'Archery                       ', N'xx xxx xxx xxxxx                                                                                    ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (107003, N'Archery                       ', N'xx xxxxx                                                                                            ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (107500, N'through shot                  ', N'xxx 150 xxxx xxx xxx.                                                                               ', 0, 100, 150, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (107505, N'fire arrow                    ', N'x xxx xxxxx                                                                                         ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (107510, N'poison arrow                  ', N'x xxx xxxxx                                                                                         ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (107515, N'multiple shot                 ', N'x xx xxx xxx xxxxx                                                                                  ', 0, 100, 99, 100, 3, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (107520, N'Guided arrow                  ', N'100 xxx xxxx xxxxx                                                                                  ', 2, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (107525, N'perfect shot                  ', N'xxx 200 xxxx xxx xxx                                                                                ', 0, 100, 200, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (107530, N'fire shot                     ', N'x xxx xx xxx xx xx xxxxx                                                                            ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (107535, N'poison shot                   ', N'x xxx xx xxx xx xx xxxxx.                                                                           ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (107540, N'arc shot                      ', N'xxx 250 xxxx xxx xxx                                                                                ', 0, 100, 250, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (107545, N'explosive shot                ', N'xx xxx xxx xxx                                                                                      ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (107550, N'viper                         ', N'xx xxx xxx xxx                                                                                      ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (107555, N'arrow shower                  ', N'xx xx xxx xxx xxxxx                                                                                 ', 0, 100, 99, 100, 5, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (107560, N'shadow hunter                 ', N'xxx 100xxxx xxx xxx 250 xxxx xxx xxx                                                                ', 2, 100, 250, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (108003, N'Archery                       ', N'xx xxxxx                                                                                            ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (108500, N'through shot                  ', N'xxx 150 xxxx xxx xxx.                                                                               ', 0, 100, 150, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (108505, N'fire arrow                    ', N'x xxx xxxxx                                                                                         ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (108510, N'poison arrow                  ', N'x xxx xxxxx                                                                                         ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (108515, N'multiple shot                 ', N'x xx xxx xxx xxxxx                                                                                  ', 0, 100, 99, 100, 3, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (108520, N'Guided arrow                  ', N'100 xxx xxxx xxxxx                                                                                  ', 2, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (108525, N'perfect shot                  ', N'xxx 200 xxxx xxx xxx                                                                                ', 0, 100, 200, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (108530, N'fire shot                     ', N'x xxx xx xxx xx xx xxxxx                                                                            ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (108535, N'poison shot                   ', N'x xxx xx xxx xx xx xxxxx.                                                                           ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (108540, N'arc shot                      ', N'xxx 250 xxxx xxx xxx                                                                                ', 0, 100, 250, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (108545, N'explosive shot                ', N'xx xxx xxx xxx                                                                                      ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (108550, N'viper                         ', N'xx xxx xxx xxx                                                                                      ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (108555, N'arrow shower                  ', N'xx xx xxx xxx xxxxx                                                                                 ', 0, 100, 99, 100, 5, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (108560, N'shadow hunter                 ', N'xxx 100xxxx xxx xxx 250 xxxx xxx xxx                                                                ', 2, 100, 250, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (108570, N'xx xxx                        ', N'xxx 100xxxx xxx xxx 300 xxxx xxx xxx                                                                ', 2, 100, 300, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (202003, N'Archery                       ', N'xx xxx xxx xxxxx                                                                                    ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (207003, N'Archery                       ', N'xx xxxxx                                                                                            ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (207500, N'through shot                  ', N'xxx 150 xxxx xxx xxx.                                                                               ', 0, 100, 150, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (207505, N'fire arrow                    ', N'x xxx xxxxx                                                                                         ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (207510, N'poison arrow                  ', N'x xxx xxxxx                                                                                         ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (207515, N'multiple shot                 ', N'x xx xxx xxx xxxxx                                                                                  ', 0, 100, 99, 100, 3, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (207520, N'Guided arrow                  ', N'100 xxx xxxx xxxxx                                                                                  ', 2, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (207525, N'perfect shot                  ', N'xxx 200 xxxx xxx xxx                                                                                ', 0, 100, 200, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (207530, N'fire shot                     ', N'x xxx xx xxx xx xx xxxxx                                                                            ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (207535, N'poison shot                   ', N'x xxx xx xxx xx xx xxxxx.                                                                           ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (207540, N'arc shot                      ', N'xxx 250 xxxx xxx xxx                                                                                ', 0, 100, 250, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (207545, N'explosive shot                ', N'xx xxx xxx xxx                                                                                      ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (207550, N'viper                         ', N'xx xxx xxx xxx                                                                                      ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (207555, N'arrow shower                  ', N'xx xx xxx xxx xxxxx                                                                                 ', 0, 100, 99, 100, 5, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (207560, N'shadow hunter                 ', N'xxx 100xxxx xxx xxx 250 xxxx xxx xxx                                                                ', 2, 100, 250, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (208003, N'Archery                       ', N'xx xxxxx                                                                                            ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (208500, N'through shot                  ', N'xxx 150 xxxx xxx xxx.                                                                               ', 0, 100, 150, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (208505, N'fire arrow                    ', N'x xxx xxxxx                                                                                         ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (208510, N'poison arrow                  ', N'x xxx xxxxx                                                                                         ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (208515, N'multiple shot                 ', N'x xx xxx xxx xxxxx                                                                                  ', 0, 100, 99, 100, 3, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (208520, N'Guided arrow                  ', N'100 xxx xxxx xxxxx                                                                                  ', 2, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (208525, N'perfect shot                  ', N'xxx 200 xxxx xxx xxx                                                                                ', 0, 100, 200, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (208530, N'fire shot                     ', N'x xxx xx xxx xx xx xxxxx                                                                            ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (208535, N'poison shot                   ', N'x xxx xx xxx xx xx xxxxx.                                                                           ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (208540, N'arc shot                      ', N'xxx 250 xxxx xxx xxx                                                                                ', 0, 100, 250, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (208545, N'explosive shot                ', N'xx xxx xxx xxx                                                                                      ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (208550, N'viper                         ', N'xx xxx xxx xxx                                                                                      ', 0, 100, 100, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (208555, N'arrow shower                  ', N'xx xx xxx xxx xxxxx                                                                                 ', 0, 100, 99, 100, 5, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (208560, N'shadow hunter                 ', N'xxx 100xxxx xxx xxx 250 xxxx xxx xxx                                                                ', 2, 100, 250, 100, 1, 0)
INSERT [dbo].[MAGIC_TYPE2] ([iNum], [Name], [Description], [HitType], [HitRate], [AddDamage], [AddRange], [NeedArrow], [AddDamagePlus]) VALUES (208570, N'xx xxx                        ', N'xxx 100xxxx xxx xxx 300 xxxx xxx xxx                                                                ', 2, 100, 300, 100, 1, 0)

ALTER TABLE [dbo].[MAGIC_TYPE2] ADD  CONSTRAINT [DF_MAGIC_TYPE2_AddDamagePlus]  DEFAULT ((0)) FOR [AddDamagePlus]

