CREATE TABLE [dbo].[MAGIC_TYPE7](
	[nIndex] [int] NOT NULL,
	[strName] [char](30) NULL,
	[strNote] [char](100) NULL,
	[byValidGroup] [tinyint] NOT NULL,
	[byNatoinChange] [tinyint] NOT NULL,
	[shMonsterNum] [smallint] NOT NULL,
	[byTargetChange] [tinyint] NOT NULL,
	[byStateChange] [tinyint] NOT NULL,
	[byRadius] [tinyint] NOT NULL,
	[shHitrate] [smallint] NOT NULL,
	[shDuration] [smallint] NOT NULL,
	[shDamage] [smallint] NOT NULL,
	[byVisoin] [tinyint] NOT NULL,
	[nNeedItem] [int] NOT NULL
) ON [PRIMARY]

INSERT [dbo].[MAGIC_TYPE7] ([nIndex], [strName], [strNote], [byValidGroup], [byNatoinChange], [shMonsterNum], [byTargetChange], [byStateChange], [byRadius], [shHitrate], [shDuration], [shDamage], [byVisoin], [nNeedItem]) VALUES (105630, N'Binding                       ', N'xxxx xxx xxxxx xxxxx                                                                                ', 0, 0, 0, 1, 0, 0, 100, 9, 10, 100, 0)
INSERT [dbo].[MAGIC_TYPE7] ([nIndex], [strName], [strNote], [byValidGroup], [byNatoinChange], [shMonsterNum], [byTargetChange], [byStateChange], [byRadius], [shHitrate], [shDuration], [shDamage], [byVisoin], [nNeedItem]) VALUES (105645, N'provoke                       ', N'xxx xx xx xxxx xxxx xxxxx xxxxx.                                                                    ', 0, 0, 0, 1, 0, 30, 100, 12, 10, 100, 0)
INSERT [dbo].[MAGIC_TYPE7] ([nIndex], [strName], [strNote], [byValidGroup], [byNatoinChange], [shMonsterNum], [byTargetChange], [byStateChange], [byRadius], [shHitrate], [shDuration], [shDamage], [byVisoin], [nNeedItem]) VALUES (106630, N'Binding                       ', N'xxxx xxx xxxxx xxxxx                                                                                ', 0, 0, 0, 1, 0, 0, 100, 9, 10, 100, 0)
INSERT [dbo].[MAGIC_TYPE7] ([nIndex], [strName], [strNote], [byValidGroup], [byNatoinChange], [shMonsterNum], [byTargetChange], [byStateChange], [byRadius], [shHitrate], [shDuration], [shDamage], [byVisoin], [nNeedItem]) VALUES (106645, N'provoke                       ', N'xxx xx xx xxxx xxxx xxxxx xxxxx.                                                                    ', 0, 0, 0, 1, 0, 30, 100, 12, 10, 100, 0)
INSERT [dbo].[MAGIC_TYPE7] ([nIndex], [strName], [strNote], [byValidGroup], [byNatoinChange], [shMonsterNum], [byTargetChange], [byStateChange], [byRadius], [shHitrate], [shDuration], [shDamage], [byVisoin], [nNeedItem]) VALUES (111730, N'Sleep Wing                    ', N'xxx xxxx 20xx xxx xxx.                                                                              ', 0, 0, 0, 2, 0, 0, 100, 20, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE7] ([nIndex], [strName], [strNote], [byValidGroup], [byNatoinChange], [shMonsterNum], [byTargetChange], [byStateChange], [byRadius], [shHitrate], [shDuration], [shDamage], [byVisoin], [nNeedItem]) VALUES (111751, N'sleep Carpet                  ', N'xxx xx xxxx 20xx xxx xxx.                                                                           ', 0, 0, 0, 2, 0, 30, 100, 20, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE7] ([nIndex], [strName], [strNote], [byValidGroup], [byNatoinChange], [shMonsterNum], [byTargetChange], [byStateChange], [byRadius], [shHitrate], [shDuration], [shDamage], [byVisoin], [nNeedItem]) VALUES (112730, N'Sleep Wing                    ', N'xxx xxxx 20xx xxx xxx.                                                                              ', 0, 0, 0, 2, 0, 0, 100, 20, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE7] ([nIndex], [strName], [strNote], [byValidGroup], [byNatoinChange], [shMonsterNum], [byTargetChange], [byStateChange], [byRadius], [shHitrate], [shDuration], [shDamage], [byVisoin], [nNeedItem]) VALUES (112751, N'sleep Carpet                  ', N'xxx xx xxxx 20xx xxx xxx.                                                                           ', 0, 0, 0, 2, 0, 30, 100, 20, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE7] ([nIndex], [strName], [strNote], [byValidGroup], [byNatoinChange], [shMonsterNum], [byTargetChange], [byStateChange], [byRadius], [shHitrate], [shDuration], [shDamage], [byVisoin], [nNeedItem]) VALUES (205630, N'Binding                       ', N'xxxx xxx xxxxx xxxxx                                                                                ', 0, 0, 0, 1, 0, 0, 100, 9, 10, 100, 0)
INSERT [dbo].[MAGIC_TYPE7] ([nIndex], [strName], [strNote], [byValidGroup], [byNatoinChange], [shMonsterNum], [byTargetChange], [byStateChange], [byRadius], [shHitrate], [shDuration], [shDamage], [byVisoin], [nNeedItem]) VALUES (205645, N'provoke                       ', N'xxx xx xx xxxx xxxx xxxxx xxxxx.                                                                    ', 0, 0, 0, 1, 0, 30, 100, 12, 10, 100, 0)
INSERT [dbo].[MAGIC_TYPE7] ([nIndex], [strName], [strNote], [byValidGroup], [byNatoinChange], [shMonsterNum], [byTargetChange], [byStateChange], [byRadius], [shHitrate], [shDuration], [shDamage], [byVisoin], [nNeedItem]) VALUES (206630, N'Binding                       ', N'xxxx xxx xxxxx xxxxx                                                                                ', 0, 0, 0, 1, 0, 0, 100, 9, 10, 100, 0)
INSERT [dbo].[MAGIC_TYPE7] ([nIndex], [strName], [strNote], [byValidGroup], [byNatoinChange], [shMonsterNum], [byTargetChange], [byStateChange], [byRadius], [shHitrate], [shDuration], [shDamage], [byVisoin], [nNeedItem]) VALUES (206645, N'provoke                       ', N'xxx xx xx xxxx xxxx xxxxx xxxxx.                                                                    ', 0, 0, 0, 1, 0, 30, 100, 12, 10, 100, 0)
INSERT [dbo].[MAGIC_TYPE7] ([nIndex], [strName], [strNote], [byValidGroup], [byNatoinChange], [shMonsterNum], [byTargetChange], [byStateChange], [byRadius], [shHitrate], [shDuration], [shDamage], [byVisoin], [nNeedItem]) VALUES (211730, N'Sleep Wing                    ', N'xxx xxxx 20xx xxx xxx.                                                                              ', 0, 0, 0, 2, 0, 0, 100, 20, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE7] ([nIndex], [strName], [strNote], [byValidGroup], [byNatoinChange], [shMonsterNum], [byTargetChange], [byStateChange], [byRadius], [shHitrate], [shDuration], [shDamage], [byVisoin], [nNeedItem]) VALUES (211751, N'sleep Carpet                  ', N'xxx xx xxxx 20xx xxx xxx.                                                                           ', 0, 0, 0, 2, 0, 30, 100, 20, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE7] ([nIndex], [strName], [strNote], [byValidGroup], [byNatoinChange], [shMonsterNum], [byTargetChange], [byStateChange], [byRadius], [shHitrate], [shDuration], [shDamage], [byVisoin], [nNeedItem]) VALUES (212730, N'Sleep Wing                    ', N'xxx xxxx 20xx xxx xxx.                                                                              ', 0, 0, 0, 2, 0, 0, 100, 20, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE7] ([nIndex], [strName], [strNote], [byValidGroup], [byNatoinChange], [shMonsterNum], [byTargetChange], [byStateChange], [byRadius], [shHitrate], [shDuration], [shDamage], [byVisoin], [nNeedItem]) VALUES (212751, N'sleep Carpet                  ', N'xxx xx xxxx 20xx xxx xxx.                                                                           ', 0, 0, 0, 2, 0, 30, 100, 20, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE7] ([nIndex], [strName], [strNote], [byValidGroup], [byNatoinChange], [shMonsterNum], [byTargetChange], [byStateChange], [byRadius], [shHitrate], [shDuration], [shDamage], [byVisoin], [nNeedItem]) VALUES (490213, N'xxx xx                        ', N'xxx xxxx 20xx xxx xxx.                                                                              ', 0, 0, 0, 2, 0, 0, 100, 20, 0, 100, 0)

