CREATE TABLE [dbo].[MAGIC_TYPE9](
	[iNum] [int] NOT NULL,
	[Name] [char](30) NULL,
	[Description] [char](100) NULL,
	[ValidGroup] [tinyint] NOT NULL,
	[NationChange] [tinyint] NOT NULL,
	[MonsterNum] [smallint] NOT NULL,
	[TargetChange] [tinyint] NOT NULL,
	[StateChange] [tinyint] NOT NULL,
	[Radius] [smallint] NOT NULL,
	[Hitrate] [smallint] NOT NULL,
	[Duration] [smallint] NOT NULL,
	[AddDamage] [smallint] NOT NULL,
	[Vision] [smallint] NOT NULL,
	[NeedItem] [int] NOT NULL
) ON [PRIMARY]

INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (107645, N'Stealth                       ', N'xxxx xx xxxx 80xx xxxxx xxxxx.                                                                      ', 0, 0, 0, 1, 2, 0, 100, 80, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (107700, N'Hide                          ', N'xxxx xx xxxx 40xx xx xxx xxxxx.                                                                     ', 0, 0, 0, 1, 1, 0, 100, 40, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (107715, N'Cat''s eyes                    ', N'xxx xx 50xx x x xx xxxx.                                                                            ', 0, 0, 0, 2, 3, 25, 100, 50, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (107735, N'Lupine Eyes                   ', N'xxx xx xxx xxx 50xx x x xx xxxx.                                                                    ', 0, 0, 0, 2, 4, 25, 100, 50, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (108645, N'Stealth                       ', N'xxxx xx xxxx 80xx xxxxx xxxxx.                                                                      ', 0, 0, 0, 1, 2, 0, 100, 80, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (108700, N'Hide                          ', N'xxxx xx xxxx 40xx xx xxx xxxxx.                                                                     ', 0, 0, 0, 1, 1, 0, 100, 40, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (108715, N'Cat''s eyes                    ', N'xxx xx 50xx x x xx xxxx.                                                                            ', 0, 0, 0, 2, 3, 25, 100, 50, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (108735, N'Lupine Eyes                   ', N'xxx xx xxx xxx 50xx x x xx xxxx.                                                                    ', 0, 0, 0, 2, 4, 25, 100, 50, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (108805, N'secrecy                       ', N'xxx xxx xxxx xx x 30xx xxxxx xxxx                                                                   ', 0, 0, 0, 1, 5, 25, 100, 30, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (207645, N'Stealth                       ', N'xxxx xx xxxx 80xx xxxxx xxxxx.                                                                      ', 0, 0, 0, 1, 2, 0, 100, 80, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (207700, N'Hide                          ', N'xxxx xx xxxx 40xx xx xxx xxxxx.                                                                     ', 0, 0, 0, 1, 1, 0, 100, 40, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (207715, N'Cat''s eyes                    ', N'xxx xx 50xx x x xx xxxx.                                                                            ', 0, 0, 0, 2, 3, 25, 100, 50, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (207735, N'Lupine Eyes                   ', N'xxx xx xxx xxx 50xx x x xx xxxx.                                                                    ', 0, 0, 0, 2, 4, 25, 100, 50, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (208645, N'Stealth                       ', N'xxxx xx xxxx 80xx xxxxx xxxxx.                                                                      ', 0, 0, 0, 1, 2, 0, 100, 80, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (208700, N'Hide                          ', N'xxxx xx xxxx 40xx xx xxx xxxxx.                                                                     ', 0, 0, 0, 1, 1, 0, 100, 40, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (208715, N'Cat''s eyes                    ', N'xxx xx 50xx x x xx xxxx.                                                                            ', 0, 0, 0, 2, 3, 25, 100, 50, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (208735, N'Lupine Eyes                   ', N'xxx xx xxx xxx 50xx x x xx xxxx.                                                                    ', 0, 0, 0, 2, 4, 25, 100, 50, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (208805, N'secrecy                       ', N'xxx xxx xxxx xx x 30xx xxxxx xxxx                                                                   ', 0, 0, 0, 1, 5, 25, 100, 30, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (490211, N'xxx x                         ', N'xx xxx xx 30xx x x xxxx.                                                                            ', 0, 0, 0, 2, 3, 25, 100, 30, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (502001, N'xxx xx(xxx)                   ', N'xxx xx(xxx)                                                                                         ', 0, 1, 5151, 3, 7, 0, 100, 3600, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (502002, N'xxxx xx(xxx)                  ', N'xxxx xx(xxx)                                                                                        ', 0, 1, 5152, 3, 7, 0, 100, 3600, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (502003, N'xxx xx(xxxx)                  ', N'xxx xx(xxxx)                                                                                        ', 0, 2, 5101, 3, 7, 0, 100, 3600, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (502004, N'xxxx xx(xxxx)                 ', N'xxxx xx(xxxx)                                                                                       ', 0, 2, 5102, 3, 7, 0, 100, 3600, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (502005, N'xxx xx(xxx)                   ', N'xxx xx(xxx)                                                                                         ', 0, 1, 5151, 3, 7, 0, 100, 3600, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (502006, N'xxxx xx(xxx)                  ', N'xxxx xx(xxx)                                                                                        ', 0, 1, 5152, 3, 7, 0, 100, 3600, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (502007, N'xxx xx(xxxx)                  ', N'xxx xx(xxxx)                                                                                        ', 0, 2, 5101, 3, 7, 0, 100, 3600, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (502008, N'xxxx xx(xxxx)                 ', N'xxxx xx(xxxx)                                                                                       ', 0, 2, 5102, 3, 7, 0, 100, 3600, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (502009, N'xxx xx(xxx)                   ', N'xxx xx(xxx)                                                                                         ', 0, 1, 5151, 3, 7, 0, 100, 3600, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (502010, N'xxxx xx(xxx)                  ', N'xxxx xx(xxx)                                                                                        ', 0, 1, 5152, 3, 7, 0, 100, 3600, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (502011, N'xxx xx(xxxx)                  ', N'xxx xx(xxxx)                                                                                        ', 0, 2, 5101, 3, 7, 0, 100, 3600, 0, 100, 0)
INSERT [dbo].[MAGIC_TYPE9] ([iNum], [Name], [Description], [ValidGroup], [NationChange], [MonsterNum], [TargetChange], [StateChange], [Radius], [Hitrate], [Duration], [AddDamage], [Vision], [NeedItem]) VALUES (502012, N'xxxx xx(xxxx)                 ', N'xxxx xx(xxxx)                                                                                       ', 0, 2, 5102, 3, 7, 0, 100, 3600, 0, 100, 0)

