CREATE TABLE [dbo].[WAREHOUSE](
	[strAccountID] [char](21) NOT NULL,
	[nMoney] [int] NOT NULL,
	[dwTime] [int] NOT NULL,
	[WarehouseData] [char](1600) NULL,
	[strSerial] [char](20) NULL,
 CONSTRAINT [PK_WAREHOUSE] PRIMARY KEY CLUSTERED 
(
	[strAccountID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[WAREHOUSE] ADD  CONSTRAINT [DF_WAREHOUSE_nMoney]  DEFAULT ((0)) FOR [nMoney]

ALTER TABLE [dbo].[WAREHOUSE] ADD  CONSTRAINT [DF_WAREHOUSE_dwTime]  DEFAULT ((0)) FOR [dwTime]

